from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
import time

# print(chrome_browser)
options = webdriver.ChromeOptions()
options.add_argument('--ignore-certificate-errors')
options.add_argument('--ignore-ssl-errors')
chrome_browser = webdriver.Chrome(options=options)
chrome_browser.maximize_window()
chrome_browser.get("https://teams.microsoft.com/")
time.sleep(5)
username = chrome_browser.find_element_by_id("i0116")
username.clear()
username.send_keys('email')
btn1 = chrome_browser.find_element_by_id("idSIButton9")
btn1.click()
time.sleep(2)
password = chrome_browser.find_element_by_id("i0118")
password.clear()
password.send_keys('password')
btn2 = chrome_browser.find_element_by_id("idSIButton9")
btn2.click()
time.sleep(1)
btn3 = chrome_browser.find_element_by_id("idBtn_Back")
btn3.click()
time.sleep(45)
btn4 = chrome_browser.find_element_by_id("app-bar-ef56c0de-36fc-4ef8-b417-3d82ba9d073c")
btn4.click()
time.sleep(5)
btn5 = chrome_browser.find_element_by_class_name("node_modules--msteams-bridges-components-calendar-event-card-dist-es-src-renderers-event-card-renderer-event-card-renderer__textBox--2IthR")
action = ActionChains(chrome_browser)
action.double_click(on_element = btn5)
action.perform()
time.sleep(3)
btn6 = chrome_browser.find_element_by_id("id__101")
btn6.click()
time.sleep(10)
btn7 = chrome_browser.find_element_by_class_name("button-command--text-with-icon")
btn7.click()
time.sleep(30)
# btn8 = chrome_browser.find_element_by_class_name("app-svg icons-call-end")
# btn8.click()
chrome_browser.quit()
chrome_browser.quit()


#powershell cmd - python3 automation.py